name: e2e
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Checkout UI
        uses: actions/checkout@v3
        with:
          repository: Yam1x/to-dos-ui
          path: to-dos-ui
        
      - name: Install devcontainers
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            kind create cluster --name to-dos --config kind-local-config.yaml --kubeconfig ./.to-dos-cluster-kubeconfig
            echo "127.0.0.1 to-dos.local.tourmalinecore.internal" | sudo tee -a /etc/hosts
            curl http://to-dos.local.tourmalinecore.internal:40080/api/to-dos-api/api
        

